### ISSUE TITLE
In Unity2017.8.  No showing properly

### ISSUE THREAD

**Issue by suntabu** [Nobinator/Unity-UI-Rounded-Corners#4]
The result showing below:
![image](https://user-images.githubusercontent.com/7839044/65847232-3ddabb80-e373-11e9-9955-87610b04aab4.png)

What's wrong with my unity, or Unity2017 does not support `fwidth` instruction?

**Comment by Nobinator** [comment]
Hi @suntabu!
I am not really sure about the reason. Unity 2017.8 also not available from Hub, and this is not LTS version. This shader uses only built-in instructions, so even if it is possible to reproduce the bug, I don't know how to fix this. It is better for you to use LTS version of Unity or another more stable version :)

**Comment by suntabu** [comment]
Hi,
Thanks for your advice and your wonderful shader code.
It's not a big problem, I added some if conditions code solved this.

**Comment by suntabu** [comment]
My solution is：
``` c
float AlphaForRoundedCorners(float2 uv, float w, float h, float r){
    float2 newUVInPixels = float2((uv.x - 0.5) * w + .5, (uv.y - 0.5) * h + .5);
    float2 muv = abs(newUVInPixels * 2 - 1) - float2(w, h) + r * 2;
    float d = length(max(0, muv)) / (r * 2);
    if(d<= 1){
        return 1;
    }
    
    return saturate((1 - d) / fwidth(d));
}

```

**Comment by Nobinator** [comment]
@suntabu Great! It would be better if we will use **max** function instead of **if statement**, so just replace 
```
float d = length(max(0, muv)) / (r * 2);
if(d<= 1){
    return 1;
}
```
with
```
float d = max(length(max(0, muv)) / (r * 2), 1);
```
and create a pull request. I am on vacation and I cannot apply code by myself. This is probably a solution for similar issue #7, so it would be great if you could send me a pull request, that guys will check the solution and then I will push this to **master**. Thanks!
